### ISSUE TITLE
Room Picture Glitch

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#101]
I noticed today when I logged in that when I move from room to room, the picture doesn't change. It stays the same as the room before it and doesn't fix itself.

It's not like that when I use a port, I don't think, but does when I use the direction links or macros.

**Comment by nickicolem** [comment]
Oh i sort of but sort of not had this problem today, when clicking between rooms the room pic took 5-10 seconds to switch to the correct one even though all the room descrip info pulled asap.

**Comment by wastedshame** [comment]
I think that this issue has been fixed. I've not encountered this problem in a few months. Closing now. Will reopen if it arises again.
