### ISSUE TITLE
Reliability and Usability of Karchan 

### ISSUE THREAD

**Issue by nickicolem** [maartenl/Land-of-Karchan#103]
Karchan at the moment is not easily usable for rp. I was talking to another roleplayer and we discussed about how hard it is for new players to play the game but also now for existing roleplayers too now.

Before when the screen refreshed the posts you had put remained there but now if your screen refreshed it completely clears. 

On most devices if you go to a different window and then return to it, the screen refreshes. This is normal for people to switch screens whilst waiting for the other person to post as they can take 10-60 minutes depending on the roleplay so if the screen refreshes on your returns abd therefore clears, you miss their post and are having to ask them to repost and this is happening several times per an rp session. And also if we try to recruit new players they wont be aware of these quirks and therefore wont be aware we might habe been trying to communicate with them therefore reducing the ability for player retention.

So if it can return to how it was it would be good and at least then a less frustrating system to roleplay on and better for potential new folk.

In a perfect world if there was a way to keep the text on your screen until you clicked quit this would be great as it would allow people to switch devices and still have their posts and what has been written accessible. I.e if i was playing on my laptop but had to pop to the shop, if I could log in on my mobile and still see all that had been written prior. This used to be what the game had many years ago and it was very handy and it would be even easier now in this day and age of multiple devices and busy lives and multi tasking. Also on the back of this with busier lives, a potential to extend the time out to two hours or more might be helpful too.

**Comment by maartenl** [comment]
Closing this. The log stays until the player indicated it should be cleared. (that is doesn't is another bug entirely)
