### ISSUE TITLE
Communication Error - Admin Pages

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#111]
I keep getting the red error below multiple times a day in the admin pages, usually when I'm in the middle of something. 

The admin pages are also very slow, and sometimes I have to hit save multiple times for things to go through.

![image](https://user-images.githubusercontent.com/7554516/83342779-4e0bb780-a2c1-11ea-829b-1397cd7afc93.png)

**Comment by maartenl** [comment]
Closing this. It refers to the old Vaadin pages which are nog longer used.
