### ISSUE TITLE
Problem logging in.

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#118]
This is a problem my wife encountered on her character Jairia. 

She logs in, and the room she's in doesn't show up, she doesn't show up on the who list, and she doesn't show up as logging in to other people. I looked up the room she was in since I was already in the admin pages, and ported to it. It shows her as being in a blank room. I ported to it, not a blank room and she isn't in it. 

I wondered if it could be because of the guild she's in (khneo), but we tried other characters of hers that are in that guild and couldn't duplicate the glitch.

I also had her try other characters to see if they were glitched too, but it seems to be just Jairia.

I'll report back to this issue if other people experience this glitch. In the meantime, is there anything I can do to fix the character Jairia? Counsel greatly appreciated. <3

Screenshot attached. 

![bug](https://user-images.githubusercontent.com/7554516/84095939-9cf6d280-a9ce-11ea-84c1-13199f2eb742.jpg)

**Comment by wastedshame** [comment]
Small update:
Two more characters are bugged. My wife's character Almahvius, and my character Leliel, who is in the same room with him.

We have a hypothesis (or my wife does) that characters that were in rooms you need commands to get into during the update somehow got messed up.

Example: Jairia was in The Broom Closet in Khneo. It needs a command to get into the room.
Almahvius and Leliel were in his chambers on Mahtohs, and you need a command to get into it.

We haven't been able to duplicate this with any other characters yet, but we're testing. I'll update again as the list grows.

**Comment by wastedshame** [comment]
Update: Phantom is also glitched. He's in a room that requires a command to get in and out.

**Comment by wastedshame** [comment]
Update: My character Nasrin is glitched. I don't remember where I logged her off last, but her home is lockable from the inside and outside.

**Comment by wastedshame** [comment]
Lanterna is glitched. I have her in an area I build for fun around Halloween that is closed the rest of the year (area is pumpkin, for Pumpkin Patch).

Adrik is glitched. Adrik is in a room that I made for him that requires a command to get in and out. Room 9870.

Alahnis is glitched. He was in his house (it says Nasrin's Home, but they're married). It has a lock on it. Nasrin is in the exact same room, but is not glitched.

**Comment by wastedshame** [comment]
I sent you a list of other glitched characters in an email.

**Comment by wastedshame** [comment]
Another affected character is Qaina. A player who hasn't logged in for awhile tried to log in at my request, but she had the same problem listed above with the blank room.

**Comment by nickicolem** [comment]
Solaris has this issue too

**Comment by maartenl** [comment]
I'll check it out.

**Comment by maartenl** [comment]
Unable to reproduce the problem on my machine. Perhaps you could help me out?

**Comment by wastedshame** [comment]
After checking the characters in question and reaching out to Solaris to see if he's still experiencing this glitch, it appears that this is no longer an issue. Closing this now.
