### ISSUE TITLE
Cant clear screen sorta

### ISSUE THREAD

**Issue by nickicolem** [maartenl/Land-of-Karchan#119]
Love love love that it keeps what prev happened for when you log in. 

However i cant clear it. I click clear, quit, log out. Log back in and it is there...and it is jist growing with every login i do lmao.  I have a video of it bit it wont allow me to attach a video here

**Comment by maartenl** [comment]
Have you tried typing "clear". And then use the "Quit" button and go to the main page of Karchan and try again?

**Comment by wastedshame** [comment]
She means that the previous logs are getting to be a lot. We like that previous sessions can be seen, but a way to clear that log and start fresh should be an option too. I know that as a deputy, I test commands a lot, so my screen is a mile long every time I log in. 

I touched on this in issue #137 without knowing @nickicolem got to it first.
