### ISSUE TITLE
Expanded Race List

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#135]
Hello Karn!

The team has been discussing some things behind the scenes that we would like to officially request from you.

Karchan right now is a very diverse game. There are a lot of different races and even mutt characters. After discussing ways the game could be improved, we thought it would be a nice feature to update the list of races people can make in the Room of Lost Souls.

We think it would show potential players that we have more to offer than the current options there.

We came up with a list of the most commonly played fantasy races in game, and it is our request that you please add these to the drop down menu as race options in the Room of Lost Souls.

Half-Elf.
Selkie.
Naga.
Nymph.
Centaur.
Elemental.
Anthro.
Demon.
Dragon.
Elemental.
Fae.
Mermaid.
Orc.
Spirit.
Werewolf.

We would also like it if there was an option to select 'vampiric' as an adjective when making a character.

It is our desire to show newbies that there are more options than human, elf, and dwarf (though all of those are popular in game as well).

If you implement our request, we came up with the following addendum (if you're willing) to add to the Room of Lost Souls:

**_If your character is a race not listed below, you can ask one of my deputies to change them into the appropriate race. You can contact them on discord or you can email them at deputies @ outlook.com.  You can also choose to send a MUDmail in game, putting 'deputies' in the to slot to contact all active deputies at once._**

If you have any questions, please let us know. We hope you will consider our requests. We want Karchan to look as inclusive as possible, and we think that expanding the race list in the Room of Lost Souls will help up our appeal.

Thank you so much and have a good day.

**Comment by maartenl** [comment]
Well, some good news. The character creation page is just a webpage and can be changed using the templates in the admin pages without changing any code

I did just that, and it should work, but it's always a good idea to verify this.

Regards,
