### ISSUE TITLE
Who list not showing idle times

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#143]
There's no idle times on the internal who list.
I tried to upload a screenshot, but it kept timing out.

**Comment by maartenl** [comment]
It's currently by design. The external who list is fine. Is it necessary for this to be fixed?

**Comment by wastedshame** [comment]
From the discord:
I gave it over a month to see what I thought of not seeing idle times, and I'm gonna say that I hate it. xD It's a helpful tool to know if we're interacting with someone who is idling and might not return, as Ephinie (Gvaudoin) mentioned. We also use it if people are close to idling out during long/big rps, so that no one misses anything by idling until their turn. If you would please, can we have it back?
