### ISSUE TITLE
Executing who command does not change idle time

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#166]
I noticed this tonight when my wife and I were writing rooms.

When I typed who, it said something like 18 min, 4 sec idle, and no matter how many times I typed who after that, it would not zero out the time.

I tested another command (i/inventory) and that seemed to work just fine, so I think that this bug may be specific to the who command.

**Comment by maartenl** [comment]
Interesting that you noticed that.

I consider it not a bug. *(let me know if you disagree)

It's how it's designed now. When you enter the "who" command, the javascript in your browser just goes to the "Who" webpage on the website and takes it information from there. It doesn't actually submit the command to the game anymore.

**Comment by maartenl** [comment]
It's my way of not having to program the same thing twice (once in the game, once on the website). I'm lazy.

**Comment by wastedshame** [comment]
Noted!

I tend to notice a lot of things. ^^;
