### ISSUE TITLE
Items.

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#17]
We cannot generate items.

**Comment by wastedshame** [comment]
We need the addItem function back soon, please. :)

**Comment by wastedshame** [comment]
I am still desperate for this, as if Ephinie. A lot of things of ours we cannot fix without the addItem function being added back. We cannot fix mining, I cannot fix my quests, I cannot fix a slew of other things that I am past ready and onto desperate to fix, PLEASE, I beg you, consider doing this soon. Ephinie won't even fix her other stuff until you give us back the addItem function because the things she wants to fix the most involve items.
I hope you read this and understand that I am begging at this point. Items are important for many reasons, and we feel severely neutered without being able to generate/program with them.
Thanks.

**Comment by maartenl** [comment]
ConstraintViolations occurred. I've tested it with the command "create signature" and it works.
