### ISSUE TITLE
Play Discussion #2

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#2]
<b>(People want deps to be able to erect new boards)
<font color=red>(P.S. I found this in admin, from your own fingers :) "Right now it is not possible to make any changes. If the need is there, I will make it possible to add, delete or change boards.")</b></font>
Eloise says : I think it would be nice to have boards in each city, so event specific to those places can be posted. If this already exists then um...someone needs to tell me where to find them, because I haven't yet.
You say [to Eloise] : Boards can only be programmed by Karn, and they were brought up during the last discussion. I will let him know that another player would like to see this happen. If deputies could make boards, I'm pretty sure there would be one in each town. I know there would be in my areas.
Ephinie agrees to you.
Dhyrhice notes that boards were brought up last week, same answer, unfortunately. :/ It would be nice to have boards, but at least there is the public and RP.
Eloise says : I read that, I promise. That's probably what put the idea in my head.

<font color=red><b>Still getting asked about personalizing guild chat colors...</b></font>
Dhyrhice still wants different guildchat colors, too...but that is a Karn thing also, I hear. xD

**Comment by maartenl** [comment]
This has already been implemented (like ages ago!)
