### ISSUE TITLE
Auto Refresh Not Working Properly

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#203]
I've been running an event with the help of Zaria's player, and some of the players involved have mentioned having issues with the game not automatically updating/refreshing. They have to hit reset or refresh the page to get new text to show up.

It happens for SOME players, SOME of the time, and browser doesn't seem to matter. It also happens not just on computers, but phones/tablets as well.

I haven't personally encountered the problem, and neither has my wife, but enough players have that I thought to address it.

I asked for clarification of the problem on the errors and glitches channel on the discord, and this is the feedback I got:

Vicci - Deputy of Karn — Yesterday at 2:22 PM
So @ here, if you've been playing Karchan any, including during the Coldridge event, can you please explain the issues you are having with auto update and reset? I'm not sure how to explain the problem as a whole, but would like to be able to write something up for the github so that @ Karn can look at it.
Please write whatever issues you are experiencing here for me.

Yamminuel/KingCockle/SweetPotato — Yesterday at 2:23 PM
It just reverts back to the how it was when you had to hit submit to refresh the page, except now it's reset and submit doesn't work.

Vicci - Deputy of Karn — Yesterday at 2:23 PM
My understanding is that auto update sometimes just doesn't work, but sometimes it does, for some people and not for others.

Yamminuel/KingCockle/SweetPotato — Yesterday at 2:24 PM
but when you hit reset everything returns, even stuff you cleared

Vicci - Deputy of Karn — Yesterday at 2:24 PM
That's actually intentional.

Jaymes and the Giant Leech — Yesterday at 2:24 PM
I don’t get auto updates. I have tried different browsers (although mainly use chrome or safari) and different devices. I will reset, reconnect, ping to confirm, etc. and I always have to refresh to see posts.

Vicci - Deputy of Karn — Yesterday at 2:24 PM
If you want to clear that permanently, you type clear instead of clicking it.
But reset is important in case you miss a post somehow.

Yamminuel/KingCockle/SweetPotato — Yesterday at 2:25 PM
ah nice
well still. auto refresh isn't working. Where's the whip

Jaymes and the Giant Leech — Yesterday at 2:26 PM
I’ve also cleared cache and cookies on my end.

Vicci - Deputy of Karn — Yesterday at 2:26 PM
I'll combine this and streamline it with concerns on the github. Thanks to you both for responding. ❤️ If anyone else is having a problem, ever, as far as errors or glitches, please post here so that we are aware of it.
I don't have these problems for some reason, but enough of you have that I want to address it. I just wasn't sure exactly what the problem was or how to phrase it, so feedback is awesome.

**Comment by maartenl** [comment]
Hmmm. This is very hard to diagnose. It completely fails to work for him? Always?

**Comment by wastedshame** [comment]
Not just him, but Jaymes' player and Ephinie as well to my knowledge.

**Comment by maartenl** [comment]
Hmmm. Stilll needs more info. Using F12 in the browser, you get a DevTools (Chrome) window, which has a Network tab showing network calls when doing stuff in game. (make sure "All" is selected, so we see all network calls.)

Things that fail should be in red.

I'm particularly interested in the WS (WebSocket) calls called "chat". Do they succeed?

**Comment by maartenl** [comment]
Best I can do, unfortunately, is make it so it automatically reconnects if it detects a lost connection.
