### ISSUE TITLE
Chatline Request (Deletion/Edit/Overwrite)

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#214]
Hi.

So I've been messing around with chatlines and realized that you can mess some up, lol.

Example is chat rajan (17) that I was trying to make last night on my kindle. I messed up the color by accident, so the chatline does not work.

It would be nice if we had a way to edit chatlines or delete them and start over, in case of screw ups like mine.

It isn't super pressing, but if it is an easy fix, it would be an amazing addition to the existing chat commands. Especially since accidents do happen. ^^

**Comment by maartenl** [comment]
Sounds great, but I've always modelled it after the chatlines in World of Warcraft. There's currently no ownership.

(in World of Warcraft the chatlines would disappear if there'd be nobody using it. The first person to enter the chatline became owner. The owner who left, caused another random person using the chatline to become owner.)

What would the requested behaviour be in this case?

**Comment by maartenl** [comment]
Of course I could make it so only admins can edit and delete chatlines.

**Comment by wastedshame** [comment]
I think having chatlines where only admins can edit and delete chatlines would be good, because sometimes accidents happen, like with the example above.

(Example is chat rajan (17) that I was trying to make last night on my kindle. I messed up the color by accident, so the chatline does not work.)

Also, I think an option to switch ownership of a chatline between players would be good too, just in case a group suddenly finds itself with a new leader or something similar. That way, there's not a "new" chatline where the other one could still be utilized? And an option for deps to switch ownership too, because sometimes player disputes do happen, and having a "just in case" in place would help navigate some of the issues there.

Hope I'm making sense. I'm very tired.
