### ISSUE TITLE
Mass Item Generation

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#221]
I've tried a bunch of different ways, and cannot get this to work. Finally decided to reach out for help.
The commands we use to generate items, only do so one at a time. In my personal method (vicitems), when I try to put in a the amount, not matter what number I type in, I still only get one.
So example:
vic 10 item 2 should give me ten picks. It gives me one.
Trying to generate extra items with macros still only generates 1 item.
Example:
vic 1 item 2 ; vic 1 item 2 ; vic 1 item 2 = should give me three picks. It only gives me one.

We used to have this functionality many years ago, but it was lost when we switched to javascript, I believe. It would be amazing to have back as now we have to type in the command, hit enter, type in the command, hit enter, type in the command, etc, to generate the number of items we want.

If this is currently possible and my method needs tweaking, please advise.

**Comment by maartenl** [comment]
Turns out the problem is identical to issue #226, but in a different part of the code. Fixing.
