### ISSUE TITLE
Attribute Situation

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#226]
I noticed the last couple of days that any command requiring setting multiple attributes will only do one or two, then just ignore the rest of the attributes I need to have set.

I tried to work around my simpler version of the method stockgrimoire by making it where you had to execute the command multiple commands for what I wanted, but it still doesn't perform as expected.

Then today, a player was helping me with bricklaying, and I realized that you can't even set multiple attributes with macros. After it sets the first, it ignores the rest.

It's very frustrating and I wish I knew a better way to explain the bug itself, but it's just not liking anything where you set multiple attributes, no matter how complicated or simple you make it. It's a major pain.

**Comment by maartenl** [comment]
You are correct in your explanation of the bug. I've fixed it. Will be included in the next release.
