### ISSUE TITLE
Weird Ownership Glitch

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#228]
I changed one of my items into something, and it let me save the first time. When I went to updated it, it told me Victoria is not the owner. Ephinie is.

The item has never belonged to Ephinie and it even shows the item as being saved in my name.

I took a screenshot to make sure I'm not just crazy. You can see that I own it but it isn't allowing me to update it.

![image](https://user-images.githubusercontent.com/7554516/226058504-1c68f1d9-5a43-4061-8e5e-1da7eee0c2f5.png)

**Comment by wastedshame** [comment]
Update: I clicked a different object, then went back, and it allowed me to update. Still a bug though.

**Comment by maartenl** [comment]
I don't think it's a bug. Well, at least I'm not sure.
The interesting thing here is that the title mentions "Item 3444" - which is owned by Victoria.
But the item id displayed in the form is "3443" - which is owned by Ephinie.

Did you change the item id in the for? And if not, any chance of finding out how it happened? Let me know.

Anyways: for updating items, the item id in the form is used. Hence the error message.

**Comment by wastedshame** [comment]
I'm going to have to be more careful when I'm scrolling, You're right. That's probably the issue.
Thank you for the comment! I'll watch what I'm doing better. :)
