### ISSUE TITLE
Clear

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#23]
If you type 'clear', it clears the screen, but it stays cleared and doesn't allow the new text to show up.

**Comment by maartenl** [comment]
Works fine in Linux/Firefox as Browser. It says "You cleared your mind." and all new text appears below that.

**Comment by wastedshame** [comment]
I use Firefox as my main browser, and when I type clear, it clears the screen but nothing I do after that shows up until I hit refresh. I know that others have expressed the same issue (Ephinie is one of them). The button works fine, but typing clear is where the issues lies.
-Nettie
 *~~~~~~~~~~*~~~~~~~~~~*~~~~~~~~~~*
“With the world always filling you, no one has to worry about what's in your mind. With everyone's imagination atrophied, no one will ever be a threat to the world.” 
  Chuck Palahniuk, Lullaby

**Comment by maartenl** [comment]
Is this fixed?

**Comment by wastedshame** [comment]
It's been fixed, yes.
