### ISSUE TITLE
Changing God

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#232]
I accidentally made a bot instead of a shopkeeper, but can't change the god from bot to shopkeeper.

Also, I can't delete bots and remake them, and I'd like to keep the name.

May we please have an option to change this depending on needs?

Thank you!

**Comment by maartenl** [comment]
What happens when you try to delete a bot? There's a delete button in the admin character page, doesn't it work?

**Comment by wastedshame** [comment]
It doesn't work for bots.
There are also come characters that cannot be deleted. I intended to delete the 'Nettie' character I made and possibly turn her into a bot, but was unable to delete the character.
For some, the delete feature works fine. For others, not so much, especially bots.

**Comment by maartenl** [comment]
About the deleting of characters: Nettie apparently has mudmails and thus I cannot delete her using the Admin. I can get an error.
Solution: upon deleting a character, automatically delete all the mudmails first. (I will implement this.)

**Comment by maartenl** [comment]
Damn, I had two different "delete" methods, one which did the proper thing and one which did the wrong thing. Consolidated. Hmm, seems I also only put in the "delete char" for actual players, fixed, now does all persons.

**Comment by wastedshame** [comment]
I was successfully able to delete 'Nettie', but still have characters that I can't delete (or rather, characters I turned into bots that I no longer want to be bots). 
Example: Tarnas has his God set to Shopkeeper. I no longer want him to be a shopkeeper, as I intend to play him. I cannot change his god to anything, and I can't delete him to start over.
