### ISSUE TITLE
Making Negative Items Getable

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#238]
There are certain negative items in rooms that need to be deleted or removed, but that's not a possibility.
If we could have negative items be toggled to getable when we want, we could use the destroy command to get rid of the item.
Currently, I cannot get the getable feature to work on negative items, which I'm sure is is on purpose.
This comes up because in trying to get the shoplist items to work, there are now two shop lists (different item #) in certain rooms and I need to delete one.
I tried making a script to delete certain items in a room, but have failed so far. I'll keep trying unless you tell me it isn't possible atm.

**Comment by maartenl** [comment]
Would it help if I added the item instances to the Items page of the Admin? Where you can remove them?

Something like:
item -2125
tattered, handwritten, for rent sign

iteminstance 1 Karn [delete]
iteminstance 2 room 1 [delete]
iteminstance 3 container 14 [delete]
iteminstance 4 Victoria [delete]

**Comment by wastedshame** [comment]
I think that would be great. :)

**Comment by wastedshame** [comment]
This is now possible, so closing.
