### ISSUE TITLE
Dark Mode Button in Game

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#242]
A player recently lamented how they wish they had access to the dark mode button once already logged in, and it didn't sound like a bad idea.

I thought I would mention this here. She briefly touched on it in the player discuss channel on the discord server.

**Comment by maartenl** [comment]
I can do this, but I do have a question about what you want:
1. have the darkmode button available in the "Settings", right above "websockets".
2. have the darkmode button available in the "Playing the game" part.

**Comment by maartenl** [comment]
For now. I've put it in the "Settings".

**Comment by wastedshame** [comment]
I asked the player that requested this what she preferred, but she hasn't seen it yet. Settings should be fine though. Thank you. :)
