### ISSUE TITLE
Damien

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#243]
I have a character named Damien that I haven't logged on in awhile.

I was looking through character sheets today, when I realized that whoever had the character before, had filled out some information. So I thought, I'll log on and erase that in the settings and update it to reflect his current family/story, etc.

I got error messages galore, and my guess is that it has to do with how the person who had the character before me entered in their family info based on the errors I received.

![image](https://github.com/maartenl/Land-of-Karchan/assets/7554516/3ea6e441-2b49-4d6c-b1e3-6a4fb39ec86d)

I also cannot play him currently due to these errors. He is the only one of my characters affected by this (that I know of).

**Comment by maartenl** [comment]
I hopefully changed the data, and it should be fixed.

Let me know.

**Comment by wastedshame** [comment]
That worked perfectly! Thank you. :)
