### ISSUE TITLE
Karchan.org Deputy Email

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#244]
So I'd like to request that there be a karchan.org email address to reach deputies, where when it is emailed by a player, it sends it to all active deputies or deputies that currently have access. My reasons for requesting such are below:

1. When someone mails the outlook email address, I am often the only active deputy/deputy that has access. So even though I see the email, I get others poking me about it specifically, and I no longer want to be on that particular email address for reasons I don't want to get into.
2. Any time that I have wanted to log into that email account on outlook, I am never able to get into it because of reasons that are unclear. Even with the password correct, it doesn't want to let me in, and sometimes everyone gets locked out of it as a result.
3. Due to the second point, when we have to remove a deputy from the deputy email address, it cannot be done easily and it is frustrating.
4. It is currently tied to a former deputy's email address, and since this person is no longer a deputy, that means one would have to go through her to make official changes (it is set up as the recovery account). This isn't feasible for a lot of reasons.

It would also be nice to be able to send a mail from this karchan.org email address in reply, without need for exposing our personal email addresses.

I suggest deputies @ karchan.org.

If you have any questions or need clarifications, please feel free to ask. I haven't been awake long and don't know if any of this makes sense.

**Comment by maartenl** [comment]
I'm quite reluctant to do this. It takes either money or effort. In the past, I ran my own email host quite badly and it takes a little thing to get banned from sending email.

**Comment by wastedshame** [comment]
What would you suggest as a good alternative for this? It is something that is needed, but I understand where you're coming from too. I'm open to suggestions on how to fix this.
Would a form people can fill out be possible with deputy-related problems work? They fill it out on the website and it sends an email to all active deputy emails? Or is that too similar to what I'm asking for above?

**Comment by maartenl** [comment]
Okay then. What could work is "email forwarding". I set something up with a free service and you can send email to karn now, for example.

Send me a **mudmail** with the email addresses and the email address you want and I'll set it up.

P.S. this is "**email fowarding**", and works fine for receiving email.

P.P.S. therefore if you wish to **SENT email,** there's two options:
1. a free workaround available on google mail (adds a ‘via gmail.com’ note to your emails)
2. a paid premium plan at the free service I signed up for (90 $ per year).

**Comment by wastedshame** [comment]
Definitely use the free workaround.
I sent you a MUDmail as requested.

**Comment by wastedshame** [comment]
I got both emails.
Don't forget to change the old deputy address on the main page to the new ones. :)
Thank you for looking further into this. It really was needed.

**Comment by maartenl** [comment]
Closing this. Open a new one if something's wrong. Contact me directly if something needs changing.

**Comment by maartenl** [comment]
Closing this. Open a new one if something's wrong. Contact me directly if something needs changing.
