### ISSUE TITLE
Sent Folder Tab

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#251]
I recently told a player that the could look in his 'Sent Folder' to see MUDmails he's sent in the past, as he was newly returned. He claimed he couldn't see any tab that said 'Sent' on it.

I showed him that it showed up for me, but the problem was that it doesn't show up in light mode. I can see it in dark mode, but he wasn't using dark mode, so he wasn't aware the tab was even there.

![image](https://github.com/maartenl/Land-of-Karchan/assets/7554516/fee11e3c-8c7f-4765-86b9-e1192db69895)

**Comment by maartenl** [comment]
It seems upgrading to Angular 18 and all dependencies has fixed it. Will be fixed in the next release.
