### ISSUE TITLE
Can't Put These Items in a Container?

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#253]
I am not sure why, but I cannot put item 66 or item 59 in a container. They don't look any different from similar items I've made.
I'm sure there is a reasonable solution to this, but I'm unsure what to do.
Is there any way you could have a look and see if the problem is on my end or not?
Thank you. :)

**Comment by maartenl** [comment]
Which container? Do you get an error message?
Try and see if you can get an error message in the Admin, tab "Systemlog" on the date that you tried it.
(Also send me the date that you tried it (and time), so I can verify in the logs on the server).

(Give me the items and a container, to see if I can do it. :) )

**Comment by maartenl** [comment]
Okay, so I fixed it in the database. Both items were containers, and containers cannot be put into containers.

It's not really your fault. The Item Admin Page does not properly handle the "container" field. Will fix in the next release.
