### ISSUE TITLE
Logon Message Html

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#255]
Html for guild messages is messed up when you login. Looks fine in guilddetails, but not when you login.

![Screenshot_20240814-034514](https://github.com/user-attachments/assets/a5d0666d-0bbc-4a3d-a606-769baca34b12)

![Screenshot_20240814-034530](https://github.com/user-attachments/assets/ad4adbeb-8c2c-4a0e-9748-ad478c5a58f0)

**Comment by wastedshame** [comment]
You mentioned (after I posted this), that this was intentional, but I remain vocal that I am not a fan of this change.
I'm willing to explore compromises, but I really, really dislike this.

**Comment by maartenl** [comment]
Good lord, that's a lot of tags. Didn't know it was used like that.

I'll get it fixed like it used to be.

Do you need it right away, for that'll mean a new release.

**Comment by wastedshame** [comment]
I would love for this to be fixed as soon as possible, but I also understand that you are a busy man and hate to be a nag (and don't want to pester you about this too much).
Would it be too difficult/time consuming to fix quickly? I don't want to apply unnecessary pressure, but it really does look awful.
