### ISSUE TITLE
Item Deletion/Browser Incompatibility

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#256]
Cannot delete item instances anywhere except my Kindle.
You said you were able to replicate the problem in your Firefox, so it is likely a browser incompatibility issue.
Placing this here, as requested.

**Comment by wastedshame** [comment]
Now we cannot delete individual item instances in admin at all. The little trash can icon doesn't show up. Would like to reopen this issue, as a result.

**Comment by maartenl** [comment]
True. The way it works is, you find out the number of the iteminstance, fill it out in the form, and press "Delete" button.

Try that. Let me know.

**Comment by wastedshame** [comment]
I have done that, but the issue is, if multiple item instances need to be deleted it, it takes forever, whereas the way with the icon was much faster.
That and the space where you copy/paste the item instance is very small both on my laptop and worse on my kindle. The other way was better because I could just go down the line and get rid of things really fast instead of copy/paste/delete over and over.

**Comment by KarchanEphinie** [comment]
I agree with Victoria. We need the button, please.
