### ISSUE TITLE
Attribute Chat

### ISSUE THREAD

**Issue by nickicolem** [maartenl/Land-of-Karchan#45]
Chat like guild chat for people with deputy attribute- if this was also kept open and programmable for any attribute it would allow more guilds to be groups and therefore allow people to be in guilds and groups e.g cult of Solol could have a chat. this might stop guilds being made for everything so people like TK could also be and knight or and ranger.

**Comment by wastedshame** [comment]
I like the thought of us being able to program our own chat lines by attribute. :)

**Comment by wastedshame** [comment]
Then we could name our chat lines whatever we wanted like DepTalk, or CultTalk.
