### ISSUE TITLE
Admin pages - events - ownership

### ISSUE THREAD

**Issue by nickicolem** [maartenl/Land-of-Karchan#50]
You can over ride an event someone else owns.

Scenario: I owned event 1731. In error Victoria meant to type 1741 but used 1731 to use an event. This removed my event and replaced with hers.

To see if it was one off error or glitch, As a test I tried using 1728 as an event as Victoria owned that one and didn't need it. It over rode her ownership of it and I know own it.

**Comment by nickicolem** [comment]
Also on this you can seem to override any ownership by creating a new one i.e a room or an item as well if you use the same room or item number when creating

**Comment by maartenl** [comment]
This is a serious problem There's two ways we can do this: 
- I fix it.
- I start on the "new and improved" admin pages where the problem does not exist.

The latter takes longer, but will have to be done anyways.

**Comment by nickicolem** [comment]
Will this be fixed on the new admin pages as still an issue currently?

**Comment by maartenl** [comment]
Definitely.

Verzonden via Yahoo Mail op Android 
 
  Op di, sep. 3, 2019 om 19:55 schreef nickicolem<notifications@github.com>:   
Will this be fixed on the new admin pages as still an issue currently?

**Comment by maartenl** [comment]
Fixed.
