### ISSUE TITLE
New Char Creation + Logging Into the Game

### ISSUE THREAD

**Issue by nickicolem** [maartenl/Land-of-Karchan#51]
This is more of a change request than an issue.

Proposed Change: When making a new character, rather than it just being created and then having to log it in separately, for the creation to actually log you in.

Why? I think we are losing potential new players because other websites, games etcetera etcetera will automatically log you in if you create a character/account. This makes them think perhaps the login hasn't worked and they try alternative names and maybe make 2-3+ chars of vaguely similar names, get frustrated and potentially give up. So think would make the process easier/more obvious.

assumed examples: e.g vulcano and vulcano7. going to assume Cane, Cerian, Hiro and Virin based on title are prob the same. Kage, KageNoToro, and Miyuki and MiyukiTora and that is just a 5 min look at char list and not indepth.

**Comment by nickicolem** [comment]
I do think we are still losing new players by this due to the new chars created and not logging on. I know asking a bit much but any chance this can be a priority? we are trying to do a recruitment drive for new players so would be ideal if it were less confusing for them. :-(

**Comment by wastedshame** [comment]
I agree with Nicki that this is important and worth looking into when you get a chance. <3

**Comment by wastedshame** [comment]
This says it was a closed issue, but I don't see where it is working. I've made a few new characters to test and see if it would automatically log me into the game, and it creates the character but doesn't give me the latter functionality.
