### ISSUE TITLE
Kicked from Game

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#54]
Karchan has been doing this thing for awhile now, where even if you're logged in, it will time you out. Your character will still be logged in, but you have to login again because it times out.

This isn't like the auto time out that removes you from the game. Sometimes you can idle anywhere from 15 minutes - 30+ minutes and it will still kick you.

**Comment by nickicolem** [comment]
On the back of this, to expand.  The game doesn't kick you out per se but it errors if you have not done something in 30 plus minutes.  therefore though the character is logged in still and hasn't timed out from the game, you have to relog in. but yes can be annoying and can lose the rp

**Comment by maartenl** [comment]
Session timeout setting in the Glassfish changed. Timeout was set to 30 minutes. Increased it to two hours. 

Please verify.

**Comment by nickicolem** [comment]
will test now and get back to you in the hour :-)

**Comment by nickicolem** [comment]
Unfortunately didn't work. I logged 'testmya' in. idled her for 43 minutes.  Came back, tried executing command and submit but it came back with the 'An error has occurred, please contact Karn or one of the deps' standard message.

**Comment by wastedshame** [comment]
I'm still experiencing this problem as well.

**Comment by maartenl** [comment]
Roger. I think I found the problem. Will be fixed with the release of a new version of the game.
