### ISSUE TITLE
Room picture changing

### ISSUE THREAD

**Issue by nickicolem** [maartenl/Land-of-Karchan#66]
Generally as a whole the deps have used photobucket to host room pictures. Photobucket isn't allowing that anymore, though the room pictures don't yet seem to be broken but likelihood is that they will stop working soon.

So therefore I was just wondering, if it is easy for you to do, isn't too much work and it is something you can do sooner than later, if you could make a command, much like the title command where you can change your pic in your title. But instead for the deps to change the room picture they are in, (as long as they are the owner) to a different one e.g command like room picture <img src=whatever the url is we want to use>

This will save a lot of time for us deps instead of doing it through the admin pages and also allow those who aren't currently payed up to still be able to make sure the room pictures can change and Karchan not be glitchy while they are not in a position to pay.

**Comment by nickicolem** [comment]
Oops I didn't think html would attempt to work here e.g a command like 'room picture html+url'

**Comment by maartenl** [comment]
Or I could automatically download all used pictures from Photobucket, host them myself, and update all picture links in the database.

**Comment by wastedshame** [comment]
That would be amazing. What should we do if we build new areas in the future? Hosting the pictures on site does seem like the best bet, but I don't know about how much work it will make for you.

**Comment by nickicolem** [comment]
as Vic said, if you could that would be an amazing life saver. tbh in terms of future rooms it doesn't matter so much if we continue as normal/as it is currently to help save data/usage you host as it is more so the vast amount of work it would currently be that is painful so future work should be fine to continue as normal.


many thanks though :-)

**Comment by nickicolem** [comment]
also...(so sorry it just dawned on me)...any chance of item pictures as well to have the same treatment? if not no worry as that won't be half as much work and item pics aren't as big of a needed as room pics.

**Comment by wastedshame** [comment]
I would like items too, but most of mine haven't been fixed from the old way (where we put them in the description with img src), so I don't think it would work. I'd gladly fix mine, but any items with html in the item name or more than one word per descriptor will not update for me.
I'm going to make a separate issue for that, more in-depth.

**Comment by maartenl** [comment]
It's done. Here's the skinny:

- I tried downloading all pictures from the rooms from photobucket. Some provided me with an error, you'll have to check what happened there.
- I added the images to karchan.org. So, the old url would be:
http://i358.photobucket.com/albums/oo28/kokcastle/stables.jpg
The new url would be:
/images/albums/oo28/kokcastle/stables.jpg
(I use "relative" urls, no need for www.karchan.org as the images are on the same website.)
- changes all picture urls of rooms that had photobucket in 'em.

You'll have to check manually, of course.

**Comment by maartenl** [comment]
Also, if you wish to use a new image, here's the three possible ways to go about it:

1. find another website that is not photobucket that allows it
2. pester me to add the image to the /images of www.karchan.org
3. upload the image yourself into the Karchan Liferay CMS (it's possible, but I don't know how)

P.S. added the list of downloaded images in this here comment.

[list.txt](https://github.com/maartenl/Land-of-Karchan/files/1123632/list.txt)

**Comment by maartenl** [comment]
Let me know if there's anything else I need to do here, otherwise I'm closing this issue.

**Comment by wastedshame** [comment]
Some of my images aren't working, and I think I know why.

Some links had %20 as markers for spaces in the link, like here:
http://i188.photobucket.com/albums/z46/roseblossomsnapdragon/The%20Starlight%20Wood/starlightblue1.jpg

While photobucket in some places added ~original to the end of the links.  Is there a way we can amend this so that links work with those issues corrected? I think those may be why some of my pictures aren't working.

Sorry for the hassle. If it is too much of a pain, let me know and I'll figure something out.

**Comment by wastedshame** [comment]
If you log in to Liferay, Content, Documents and Media. I created a folder and put one image in it, and I can view it only when I am logged into Liferay. If I try to access the image when not logged in, it turns up broken.

I'm trying to figure out how to upload the images there to save you any more hassle. I can upload them, but hit the above snag. Advice would be awesome. It won't even generate a preview for me.

The image I uploaded is in /images/jpg/StarlightWood/waterfall1.jpg

**Comment by wastedshame** [comment]
Okay, scratch that. That one image is now working in the room it belongs in, randomly. It's room 8031. Going to work on more and see how it goes.

**Comment by maartenl** [comment]
I found and fixed two errors in my conversion script:
1. as you mentioned above, the %20 conversion to "space" didn't take place. Changed some directories to fix it.
2. also, images with extention ?t=2357646 stuff went wrong. Fixed this also.

Most images work now.

The following images are not available, as I failed to download them from Photobucket (probably):
http://www.karchan.org:8080/images/albums/qq358/graphicality/sirens_ball_foyer_zpsd6587bbe.jpg:
--
http://www.karchan.org:8080/images/albums/qq269/dramaticrper/alpha_zps8gj7xfh1.gif:
http://www.karchan.org:8080/images/albums/qq269/dramaticrper/infirmary_zpsby17okqd.gif:
http://www.karchan.org:8080/images/albums/qq269/dramaticrper/closet_zpsd5y5pvzo.gif:
--
http://www.karchan.org:8080/images/albums/k190/Ephinie/Karchan%20room%20pictures/15919466-b4c3-46bc-8cd6-af7c05e5ef81_zps56d1f0f:
http://www.karchan.org:8080/images/albums/k190/Ephinie/Karchan%20room%20pictures/93670873-6a8e-45f1-837d-d4aa6037b15c_zps4b1852d:
--
http://www.karchan.org:8080/images/albums/qq269/dramaticrper/guest_zpsvcv6o6tr.gif:
--
http://www.karchan.org:8080/images/albums/z46/roseblossomsnapdragon/kijdasshack.jpg:
--
http://www.karchan.org:8080/images/albums/k190/Ephinie/Karchan%20room%20pictures/fc06856f-09e3-43c5-86ce-15ead7a180f8_zps09504ca:
http://www.karchan.org:8080/images/albums/k190/Ephinie/Karchan%20room%20pictures/03a6f67f-a35a-494d-9099-301de975c8aa_zps5f98030:
--
http://www.karchan.org:8080/images/albums/y218/nihilityrue/Lochlen/emlodgeview1.jpg:
--
http://www.karchan.org:8080/images/albums/ff15/ParanoidCasey/piarate-barbe.jpg?t=1229044873%3E%20The%20Buccaneer:
--
http://www.karchan.org:8080/images/albums/t77/wastedshame/mini-dep/ronan/gunsinter.jpg%3E%20Hurtz:
--
http://www.karchan.org:8080/images/albums/z46/roseblossomsnapdragon/Gyllene/forest3.jpg:
--
http://www.karchan.org:8080/images/albums/z46/roseblossomsnapdragon/blaiseliving.jpg:
http://www.karchan.org:8080/images/albums/z46/roseblossomsnapdragon/blaiseroom.jpg:
http://www.karchan.org:8080/images/albums/z46/roseblossomsnapdragon/blaisecellar_1.jpg:

**Comment by nickicolem** [comment]
closing as this is all good now
