### ISSUE TITLE
Sorting Commands by Method Name

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#71]
So I have been trying to track down one of my commands all night. I know the method name, but I can't find the command attached to it because I've done so much programming in the 6 years that I've been a dep that it is literally like a needle in a haystack.

If you get a moment, would you please make it where we can sort commands by method name alphabetically or type in the method name and get the command? Thank you!

**Comment by maartenl** [comment]
The new method admin page will show you which commands use a method.

The new room admin page will show you which commands are usable in that room.

Will that suffice? If so, we can close this one.

**Comment by wastedshame** [comment]
That sounds like it will be helpful, yes.

To clarify, will we be able to search commands like methods? There's some old programming I'm thinking of getting rid of, but it's hard to search through thousands of commands just to disable one thing with no search option. To be able to see the command attached to the method would be excellent. I just want to make sure I'm reading correctly.

If that's the case, it sounds great and I feel confident saying it can be closed. :)
