### ISSUE TITLE
Non binary gender option

### ISSUE THREAD

**Issue by nickicolem** [maartenl/Land-of-Karchan#72]
I think we need to include a non binary gender option in character creation and that means we will need the program updated as well so %THISHER etc etc has something that would also cover.

**Comment by Midevia** [comment]
I would also love to see this.

**Comment by maartenl** [comment]
Can I have some more info on this, please?

Right now there's male/female, and his/her and he/she.

What specific alternatives do you suggest?

**Comment by Midevia** [comment]
They/Them/Their

**Comment by maartenl** [comment]
Hmmm. I don't like they/them/their, as it means I'll have to conjugate my verbs.

For example:
Karn=he, Maria=she, Slartibartfast=genderneutral
Karn wields his pick with great strength. He works very hard.
Maria wields her pick with great strength. She works very hard.
Slartibartfast wield their pick with great strength. They work very hard.

An alternative:
http://web.mit.edu/trans/GenderNeutralPronouns.pdf
https://en.wikipedia.org/wiki/Spivak_pronoun

**Comment by wastedshame** [comment]
I think that I would rather have they/them/their and have the verbs be wonky than move to pronouns that are lesser known or not widely accepted. Adding a non-binary gender option is supposed to help with inclusion, and the best way to do that is to use the more widely accepted pronouns.

**Comment by nickicolem** [comment]
I also share Victoria' line of thinking and would prefer going down the line of using what is widely accepted and having a few scripting quirks than going with terms that are not always recognised.

**Comment by maartenl** [comment]
You got it.
