### ISSUE TITLE
Submit Bar

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#75]
The submit bar is at the very bottom of the page without any space between it and the bottom part of the browser. Request that there be at least a few break tags under it if you plan on keeping it there. <3 Thanks.

**Comment by maartenl** [comment]
The submit bar during game play?

**Comment by wastedshame** [comment]
Yes. It fits very snugly against the bottom of the screen. I don't mind the submit bar being there, but a few <BR> after the submit bar to space it a bit better would be preferable.

I use firefox. I don't know if the issue occurs in other browsers.

**Comment by maartenl** [comment]
Fixed due to restyling of the page.
