### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Anshera** [maartenl/Land-of-Karchan#79]
I was speaking to a friend last night who I had invited to Karchan. They told me they had checked out the site, but the white background with black text was too bright for them and asked if we had a night mode. So consider this my request to have a dark mode or the option for players to adjust the background colour and text to something that suits them.

**Comment by wastedshame** [comment]
I second that a dark mode would be nice. The bright white background hurts my eyes more lately, and on other sites where there is a dark mode option, I find that I am using that more and more.

Is there an easy way to do this or toggle this?

**Comment by Anshera** [comment]
Yeah, it tends to be an issue for me as well. My eyes are pretty light sensitive and I set dark mode on anything I possibly can. So if it's possible, please consider it.
