### ISSUE TITLE
Admin pages are broken.

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#81]
Leaving a note here like you asked. Attaching the screenshot I took as well.
![brokenadminpages](https://user-images.githubusercontent.com/7554516/55345751-af968300-547e-11e9-86a4-62fdde4026bd.jpg)

**Comment by maartenl** [comment]
As always I am stuck between two choice: 
1. get this fixed pronto (don't know how easy it is, might not be easy, might be)
2. implement all admin pages in the new admin app pronto.

**Comment by maartenl** [comment]
Never mind! Fixed! Good luck. (I removed date field from Banned names and Bantable, a small price to pay)
