### ISSUE TITLE
High Priority - Attributes

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#82]
Commands that set attributes are not working.

Examples of commands like these are:
pegasus1 (which I was working on yesterday when I noticed the issue)
startingcave (for newbies)
xattribute (which is important because it is the deputy command to put an attribute on someone)

It might be worth it to check the removeattribute function too.

Thanks!

**Comment by wastedshame** [comment]
This still does not work for me. I cannot set attributes with any commands I make.

**Comment by maartenl** [comment]
Aye. I should explain how this works. 
1. I solve the issue
2. I check in the changes into source code (github automatically closes the issue for me)
3. I release the new version onto www.karchan.com

Point three hasn't happened yet. There's some more things to go into the 2.0.2 release.
