### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#83]
I'm experiencing a problem where when I try to scroll down the list of commands, the list starts scrolling automatically and I can't get it to stop. I'm not sure what could be causing this but it is very annoying as I can't get it to stop, making looking for certain commands a huge pain in the butt.

**Comment by wastedshame** [comment]
Closing this for now, as it may be a Firefox issue instead of a game issue.

**Comment by wastedshame** [comment]
Still experiencing this problem and no longer thing it is on my end. I thought it might be because autoscroll was enabled in my browser, but I fixed that and I am still experiencing the non-stop scrolling. It's really annoying.

**Comment by wastedshame** [comment]
Addendum: It's impossible to do anything in the current admin pages without normal scrolling. I literally cannot do anything I want to do and it is frustrating.

**Comment by wastedshame** [comment]
Still experiencing this and I no longer thing it might be on my end. It's making it really hard to navigate the admin pages as it just keeps scrolling even when I stop.

**Comment by maartenl** [comment]
Have you tried a different browser?

**Comment by wastedshame** [comment]
Tested it in edge, and sometimes it happens, sometimes it doesn't. I tried it on my wife's computer to see if it was just my computer, but the scrolling issue occurred on hers as well.

**Comment by maartenl** [comment]
Does this also happen with the new admin pages?

If not, we might be able to close this one.

**Comment by wastedshame** [comment]
It does not, but I've noticed that it doesn't load all of the methods or rooms either. It gets to a certain stage and just gives up on loading them all.

![image](https://user-images.githubusercontent.com/7554516/70273349-e47a7880-1777-11ea-99a4-be4a8197b11d.png)

**Comment by maartenl** [comment]
Damn. The way it works is, that not the entire list is loaded all in one go.

It loads more as you scroll down.

You mention that this part does not happen.

Do you see something in the Developer Tools Console?

What version of browser are you using?

**Comment by wastedshame** [comment]
Firefox 71.0 (64 Bit)
I'm up to date as far as the browser goes.
