### ISSUE TITLE
High Priority - guildapply

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#84]
Much like the setting of attributes (Issue #82, I believe), when you try to guildapply to a guild, it will not go through. If you refresh, you get the text You have guildapplied to (guild name here), but it actually never goes through. You don't show up in the hopefuls for the guild you've applied to even though it tells you that you have. The command just never goes through and sits there long after you've hit enter without actually working.

**Comment by wastedshame** [comment]
This still isn't working. I tested it today and had this conversation on the discord with a player.

Aildre in WonderlandToday at 9:56 AM
alright I applied
 
Victoria - Goddess of FuryToday at 9:56 AM
you're not showing up as a hopeful
 
Aildre in WonderlandToday at 9:57 AM
You have applied to guild Divine Fury.
You have applied to guild Divine Fury.
 
Cath HauntToday at 9:57 AM
Not slow for me today!
 
Aildre in WonderlandToday at 9:57 AM
log out and back in
 
Victoria - Goddess of FuryToday at 10:00 AM
so it still isn't working
Internet is trying to go out because it's raining
Internet had a hiccup
it says you've applied, but you don't show up as a hopeful where I can accept you
Keira does not wish to join your guild.
Keira does not wish to join your guild.
Thanks for the feedback, guys :heart:

**Comment by maartenl** [comment]
Aye. I should explain how this works. 
1. I solve the issue
2. I check in the changes into source code (github automatically closes the issue for me)
3. I release the new version onto www.karchan.com

Point three hasn't happened yet. There's some more things to go into the 2.0.2 release.
