### ISSUE TITLE
Random Error when I try to login to Karchan

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#86]
My wife and a couple of other players have told me about an error they were experiencing when they try to login lately. Tonight, I got the error message.

At first it says Warning 200 OK, but then changed to 200 OK after minute or so. I couldn't log in. My wife says that it happens to her regularly but thought it was our connection, but I'm not convinced it is.

Also, logging in takes ages lately.

![error1](https://user-images.githubusercontent.com/7554516/59636300-2c9dd400-9121-11e9-81e0-d6ac1ee01756.jpg)

Nat/Anshera says she has experienced this before as well.

**Comment by maartenl** [comment]
Can you give me more information on this? Is it really the network round trip that takes that much time?

**Comment by wastedshame** [comment]
I haven't had this error for quite some time now. 
Karchan still has a lot of lag at times though. Most of the lag I experience is when I'm trying to log in or out.

**Comment by wastedshame** [comment]
I haven't experienced this in awhile, so I'm going to close the issue for now. If it crops back up at some point, I will make a new issue.
