### ISSUE TITLE
Submit does not reset idle time

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#87]
Currently, hitting submit in game does not restart your idle time. You can sit in the game and hit submit over and over but still idle out after a certain amount of time.

Anshera mentioned it would be nice to have that small thing fixed and I told her I'd put it up as an issue for you to consider.

**Comment by maartenl** [comment]
Hi, I'm going to release the new version of the game. A lot has changed, and it's possible that the problem no longer occurs.

Let me know here, if it is still a problem.
