### ISSUE TITLE
Blue bar for mobile users

### ISSUE THREAD

**Issue by nickicolem** [maartenl/Land-of-Karchan#88]
We have quite a few mobile users and on the new layout of logging in it isnt going to be intuitive for them as the bluebar has no options showing in portrait set up which is what peoole primarily use, onlt horizontal will it show.
![Screenshot_20190831-002535_Chrome](https://user-images.githubusercontent.com/8420847/64055755-7164d300-cb86-11e9-8233-6d0b100ff693.jpg)
![Screenshot_20190831-002528_Chrome](https://user-images.githubusercontent.com/8420847/64055756-7164d300-cb86-11e9-8947-5516e01660f7.jpg)

**Comment by maartenl** [comment]
For small screens the links are too much and it wraps ugly.
I put the links in the menu as well if you click on the dragon. It's the last option called "personal". But that might not be as obvious.
What you think?

Verzonden via Yahoo Mail op Android 
 
  Op za, aug. 31, 2019 om 1:29 schreef nickicolem<notifications@github.com>:   
We have quite a few mobile users and on the new layout of logging in it isnt going to be intuitive for them as the bluebar has no options showing in portrait set up which is what peoole primarily use, onlt horizontal will it show.

**Comment by nickicolem** [comment]
I think for ease of access especially with potential new players -  at the very least, Play needs to be there visible. On the small blue bar, also probably on big blue bar as well on computer screens as settings isnt intuitive to click on to find play.  I think play needs to be it's own and first option and visible straight away on all devices.

**Comment by maartenl** [comment]
Agreed

Verzonden via Yahoo Mail op Android 
 
  Op za, aug. 31, 2019 om 10:36 schreef nickicolem<notifications@github.com>:   
I think for ease of access especially with potential new players - at the very least, Play needs to be there visible. On the small blue bar, also probably on big blue bar as well on computer screens as settings isnt intuitive to click on to find play. I think play needs to be it's own and first option and visible straight away on all devices.
