### ISSUE TITLE
You are not logged in as undefined - High Priority

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#90]
No longer get "null", but now, "undefined". The character is on the who list, but I didn't actually get into the game.

Wife had same problem.

![image](https://user-images.githubusercontent.com/7554516/64070656-76cc2700-cc33-11e9-8ea9-9d7d767cb0a0.png)

Note: My character Annwyn, I could get in as. I haven't test others, but Victoria still can't get in. Wife tried to log in as character Annika.

**Comment by wastedshame** [comment]
Leaving a comment to say put this on hold. I just got in as Victoria.

**Comment by Anshera** [comment]
I actually get that, and can't get in as any character -- so i'd reopen this one.

**Comment by maartenl** [comment]
Damn. Can you get me a little more info, Anshera? In the network tab of your browser, check play.js file and send it to me.

**Comment by Anshera** [comment]
Really odd - suddenly today it's logging me in just fine.

**Comment by Anshera** [comment]
Ah, it's still not logging me out though. I'm showing up on the who even though I logged out.

**Comment by maartenl** [comment]
Hmmm. How did you log out? If you:
1. log out, using the [Log out] option
2. but did NOT use the "Quit" button during the play session,

you will still be playing (even though logged out).

Is that correct? Please verify.

**Comment by Anshera** [comment]
Yeah that was the case. It's a bit confusing to be honest.

**Comment by maartenl** [comment]
Can I close it?

**Comment by Anshera** [comment]
I believe so.
