### ISSUE TITLE
Dark Mode Room Titles MASSIVE

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#91]
In dark mode, room titles and anything requiring h1, 2, or 3 tags are HUGE. I noticed it when I was programming something today and thought I would show you a comparison.

Same room. Center of Guilds.

![image](https://user-images.githubusercontent.com/7554516/64132309-e7db1e00-cd9c-11e9-9872-4abe95b9c4c6.png)

Just thought you'd want to know. When I noticed, it surprised me.

**Comment by maartenl** [comment]
Aye, the normal mode uses bootstrap. The darkmode uses a bootstrap theme called Cyborg from https://bootswatch.com.

The question, of course, is it a problem?

**Comment by nickicolem** [comment]
Sorry this isnt related to dark mode room titles but is just a query re dark mode so thought i would ask here as not an issue. Out of curiosity is there a way when making a script for a command for the font to be either one colour if darkmode is off and then a different colour of dark mode is on? If so, any chance you could make simple dummy command showing this so we can look at it? If it is a hassle or not easily possible then no worries it was just out of curiosity is all as we have quite a few commands with colour fonts and what works for one mode does not work for the other always.

**Comment by wastedshame** [comment]
It's not a huge problem, but it does make certain rooms not aesthetically pleasing. I will post a screenshot when I find another room like it for visual reference.

**Comment by maartenl** [comment]
Darkmode:
h1: 4rem

Normal mode:
h1: 2.5 rem
