### ISSUE TITLE
[High Priority] Cannot create new rooms or edit existing rooms

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#94]
I tried today in both FF and Chrome, and neither of them would let me create a new room.

**Comment by maartenl** [comment]
I assume you mean in the new admin pages I just released?

Did you get an error message? A standard "Bad Request" or "Internal Server Error" or something?

Tell me the steps that you tried.

**Comment by wastedshame** [comment]
First I tried the old admin pages, the way that I've always created new rooms. Found a room I already owned, hit create, filled in the appropriate room number and information, then clicked save. Only they didn't save. Ever.

When that didn't work, I attempted to make them in the new admin pages, but that didn't work either.

**Comment by wastedshame** [comment]
And no, no error. I didn't receive any errors. The page just wasn't created.
