### ISSUE TITLE
HTML not working

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#99]
HTML in items and rooms doesn't appear to be working. I know this because my atlas (item 706) is completely busted.
It had an iframe, a textarea, and a table with different commands all having to do with moving around the game. A player brought it to my attention when she went to use it and could not (it has an iframe that gives macros to different areas in game).
I'm really upset by this. I worked hard on the atlas and it is useful and helps people get around.

**Comment by wastedshame** [comment]
This also means that all of the maps I programmed into game using iframes and google sheets are now broken. :(

**Comment by maartenl** [comment]
Well, I am not surprised. The game itself is now also using Angular, and iframes are a bit of a security concern.
They are probably automatically filtered out.

Can you explain how it should work, and where to find it? I'll see about getting you a replacement.

**Comment by wastedshame** [comment]
I've been using iframes for guild commands and the like, but also things like my atlas.

My atlas has an iframe in it that lists a bunch of macros to get to various places easily. It also has commands attached to it that show iframes of maps of the locations in game for those who don't understand/don't like macros.

The maps I've made are on google sheets for easy editing as the game changes, and it changes a LOT.

The atlas has a list of the maps I've programmed (which now no longer work). I thought iframes were a good way to give people a map without having to leave the game.

Example of a map here: [Frosthaven Map](https://docs.google.com/spreadsheets/d/1dOC-u-_IObnDxudxFs8DJaT6iqSJRdVBpOcwIDPFZDs/edit?usp=sharing)

There are other examples of things that are now busted that I've programmed, but I can probably find some kind of work around for those. The atlas is definitely vexing me though. I've spent months and months making macros and mapping the various areas in game only for it to now be busted. I'm very upset about this.

I had tried to make the atlas before using other methods instead of iframes, but they were not successful, especially because of the semi-colons needed for the macros breaking the commands. And when I swapped out the semi-colons for XML, the commands broke too, likely because of the sheer length of the macro section.

The atlas is supposed to look like this when you type read atlas for reference:
[Atlas](https://karchanhelp.webs.com/closets/macaroninoodles.htm)

**Comment by wastedshame** [comment]
Just as a small note, I tried to work around the no iframe bit with textareas and contenteditables, even scrollable divs. None of those worked either.
My last attempt will always be the command _test atlas_, the method is _vicproblem_, and the world attribute is _vic.test_.

I consider the atlas important because it has macros that show how to get around Karchan. The comment above this one has a link to show you. My atlas item basically has a list of commands to teach people about each area in game, and now has links to all of the maps instead of using an iframe to display the map in game. The only part I cannot get to work is displaying the macros  since the content is so large and I no longer have use of iframes or textareas.

Counsel is greatly appreciated.

**Comment by wastedshame** [comment]
Found a workaround. Closing for now.
